version: 2.1

orbs:
    node: circleci/node@5.0.1

jobs:
    build:
        working_directory: ~/express-example
        docker:
            - image: circleci/node:16
            - image: docker:19.03.14

        steps:
            - checkout
            - setup_remote_docker
            - run: npm cache clear --force
            - run:
                  name: Update NPM version
                  command: 'sudo npm install -g npm@latest'
            - run: npm install
    deploy:
        machine:
            enabled: true
        working_directory: ~/express-example
        steps:
            - add_ssh_keys:
                  fingerprints: 'ef:c1:b9:b9:44:e0:54:07:df:ec:65:a1:7f:60:d1:5e'
            - run:
                  name: Deploy via ssh
                  command: |
                      echo Starting deploy to server
                      ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST 'cd ~/express-example && git fetch origin && git checkout main && git fetch origin && git reset --hard origin/main && sudo chmod 777 ./script/deploy.sh && ./script/deploy.sh'
workflows:
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - main