version: 2.1

orbs:
    node: circleci/node@5.0.1

jobs:
    build:
        working_directory: ~/express-example
        docker:
            - image: circleci/node:16
            - image: docker:19.03.14

        steps:
            - checkout
            - setup_remote_docker
            - run: npm cache clear --force
            - run:
                  name: Update NPM version
                  command: 'sudo npm install -g npm@latest'
            - run: npm install
    deploy:
        machine:
            enabled: true
        working_directory: ~/express-example
        steps:
            - add_ssh_keys:
                  fingerprints: '85:eb:15:5d:bd:1c:6b:90:f3:31:31:11:e1:39:27:66'
            - run:
                  name: Deploy via ssh
                  command: |
                      echo Starting deploy to server
                      ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST 'cd ~/express-example && git checkout main && git pull && chmod 777 ./script/deploy.sh && ./script/deploy.sh'
workflows:
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - main