version: 2.1

orbs:
    node: circleci/node@5.0.1

jobs:
    build:
        working_directory: ~/express-example
        docker:
            - image: circleci/node:16
            - image: docker:19.03.14

        steps:
            - checkout
            - setup_remote_docker
            - run: npm cache clear --force
            - run:
                  name: Update NPM version
                  command: 'sudo npm install -g npm@latest'
            - run: npm install
    deploy:
        machine:
            enabled: true
        working_directory: ~/express-example
        steps:
            - add_ssh_keys:
                  fingerprints: '47:43:43:ab:d5:da:15:40:54:b8:4a:d7:9e:53:a0:b2'
            - run:
                  name: Deploy via ssh
                  command: |
                      echo Starting deploy to server
                      ssh $SSH_USER@$SSH_HOST 'cd /home/phamhongphuc1403/express-example && git fetch origin && git checkout main && git pull origin main && pwd && sudo chmod 777 ./script/deploy.sh && ./script/deploy.sh'
workflows:
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - main